export const ENTITIES_ADD = 'ENTITIES_ADD';

export const UPLOADER_STATE = 'UPLOADER_STATE';
export const SUBSCRIBER_STATE = 'SUBSCRIBER_STATE';
export const LIKE_STATE = 'LIKE_STATE';
export const COMMENT_STATE = 'COMMENT_STATE';

export const ROUTE_LOGIN_STATE = 'ROUTE_LOGIN_STATE';
export const ROUTE_SESSION_STATE = 'ROUTE_SESSION_STATE';

export const ROUTE_HOME_STATE = 'ROUTE_HOME_STATE';
export const ROUTE_HOME_PREPEND = 'ROUTE_HOME_PREPEND';
export const ROUTE_HOME_APPEND = 'ROUTE_HOME_APPEND';

export const ROUTE_POST_STATE = 'ROUTE_POST_STATE';
