export const ENTITIES_ADD = 'ENTITIES_ADD';

export const POSTS_APPEND = 'POSTS_APPEND';
export const POSTS_PREPEND = 'POSTS_PREPEND';
export const POSTS_REPLACE = 'POSTS_REPLACE';

export const USER_POSTS_APPEND = 'USER_POSTS_APPEND';
export const USER_POSTS_PREPEND = 'USER_POSTS_PREPEND';
export const USER_POSTS_REPLACE = 'USER_POSTS_REPLACE';

export const SERVICE_WORKER_STATE = 'SERVICE_WORKER_STATE';
export const UPLOADER_STATE = 'UPLOADER_STATE';
export const SUBSCRIBER_STATE = 'SUBSCRIBER_STATE';
export const LIKE_STATE = 'LIKE_STATE';
export const COMMENT_STATE = 'COMMENT_STATE';

export const ROUTE_LOGIN_STATE = 'ROUTE_LOGIN_STATE';
export const ROUTE_SESSION_STATE = 'ROUTE_SESSION_STATE';
export const ROUTE_HOME_STATE = 'ROUTE_HOME_STATE';
export const ROUTE_POST_STATE = 'ROUTE_POST_STATE';
export const ROUTE_USER_PROFILE_STATE = 'ROUTE_USER_PROFILE_STATE';
export const ROUTE_USER_POSTS_STATE = 'ROUTE_USER_POSTS_STATE';
